### ISSUE TITLE
Boot directly to SNES emulator

### ISSUE THREAD

**Issue by mashers** [rmaz/rpi-emulator-buildroot#8]
Hi,

Thanks for putting this together. I am using a Pi2 inside a SNES case mod. It uses a Retrode USB cart interface to load the ROM directly from a real SNES cart. This works well, but boot time is slow. I'm hoping your buildroot environment might make for a faster boot time.

Do you know if it would be possible to modify this to boot directly to the SNES emulator? Also, do you know if this could then boot a ROM from a specified path?

Sorry of this isn't the correct way to contact you to ask about this, but I couldn't find any contact details, and although I'm able to tinker with Linux, I don't really know anything about buildroot.

Thanks in advance!

**Comment by rmaz** [comment]
Yes, this was my main motivation too. There are much more recent forks of this that you may be interested in, such as https://github.com/recalbox/recalbox-buildroot. Basically you can just configure the init script of the buildroot to start whatever application you choose that you have installed on the device, check the boards fsoverlay options: https://github.com/rmaz/rpi-emulator-buildroot/commit/210b817851bc5e1add02bce7bfff1a05893d249f
